version: '3' 
services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: database
    image: mysql:8.0
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: rnkj8918_bld_parfume
      MYSQL_USER: loic
      MYSQL_PASSWORD: admin
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
