<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4nyxpRkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4nyxpRk' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4nyxpRk'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryNotificationRepository' => ['privates', 'App\\Repository\\CategoryNotificationRepository', 'getCategoryNotificationRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categoryNotificationRepository' => 'App\\Repository\\CategoryNotificationRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
