<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E9w1_NGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E9w1.nG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.E9w1.nG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contentTagRepository' => ['privates', 'App\\Repository\\ContentTagRepository', 'getContentTagRepositoryService', true],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'contentTagRepository' => 'App\\Repository\\ContentTagRepository',
            'validator' => '?',
        ]);
    }
}
