<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RtvJSVsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rtvJSVs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rtvJSVs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contentTagRepository' => ['privates', 'App\\Repository\\ContentTagRepository', 'getContentTagRepositoryService', true],
        ], [
            'contentTagRepository' => 'App\\Repository\\ContentTagRepository',
        ]);
    }
}
