<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZsQAMRzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZsQAMRz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ZsQAMRz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'wishlist' => ['privates', '.errored..service_locator.ZsQAMRz.App\\Entity\\Wishlist', NULL, 'Cannot autowire service ".service_locator.ZsQAMRz": it needs an instance of "App\\Entity\\Wishlist" but this type has been excluded in "config/services.yaml".'],
        ], [
            'wishlist' => 'App\\Entity\\Wishlist',
        ]);
    }
}
