<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1gTJrcService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d1gTJrc' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.d1gTJrc'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reviewPerfumeNoteRepository' => ['privates', 'App\\Repository\\ReviewPerfumeNoteRepository', 'getReviewPerfumeNoteRepositoryService', true],
        ], [
            'reviewPerfumeNoteRepository' => 'App\\Repository\\ReviewPerfumeNoteRepository',
        ]);
    }
}
