<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BjMlj7VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BjMlj7V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BjMlj7V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'file' => ['privates', '.errored..service_locator.BjMlj7V.Symfony\\Component\\HttpFoundation\\File\\UploadedFile', NULL, 'Cannot autowire service ".service_locator.BjMlj7V": it references class "Symfony\\Component\\HttpFoundation\\File\\UploadedFile" but no such service exists.'],
        ], [
            'file' => 'Symfony\\Component\\HttpFoundation\\File\\UploadedFile',
        ]);
    }
}
