<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__AXEy8VService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..aXEy8V' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator..aXEy8V'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'checkList' => ['privates', '.errored..service_locator..aXEy8V.App\\Entity\\CheckList', NULL, 'Cannot autowire service ".service_locator..aXEy8V": it needs an instance of "App\\Entity\\CheckList" but this type has been excluded in "config/services.yaml".'],
        ], [
            'checkList' => 'App\\Entity\\CheckList',
        ]);
    }
}
