<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMyFavoriteTypesOfPerfumesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Yv6xARz.App\Entity\MyFavoriteTypesOfPerfumes' shared service.
     *
     * @return \App\Entity\MyFavoriteTypesOfPerfumes
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.Yv6xARz": it needs an instance of "App\\Entity\\MyFavoriteTypesOfPerfumes" but this type has been excluded in "config/services.yaml".');
    }
}
