<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerfumeTrialSheetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.J38_oCQ.App\Entity\PerfumeTrialSheet' shared service.
     *
     * @return \App\Entity\PerfumeTrialSheet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.J38_oCQ": it needs an instance of "App\\Entity\\PerfumeTrialSheet" but this type has been excluded in "config/services.yaml".');
    }
}
