<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReviewPerfumeNoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.6MtxQHl.App\Entity\ReviewPerfumeNote' shared service.
     *
     * @return \App\Entity\ReviewPerfumeNote
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.6MtxQHl": it needs an instance of "App\\Entity\\ReviewPerfumeNote" but this type has been excluded in "config/services.yaml".');
    }
}
