<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\UserController' shared autowired service.
     *
     * @return \App\Controller\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/UserController.php';
        include_once \dirname(__DIR__, 4).'/vendor/twilio/sdk/src/Twilio/Base/BaseClient.php';
        include_once \dirname(__DIR__, 4).'/vendor/twilio/sdk/src/Twilio/Rest/Client.php';
        include_once \dirname(__DIR__, 4).'/vendor/drewm/mailchimp-api/src/MailChimp.php';

        $container->services['App\\Controller\\UserController'] = $instance = new \App\Controller\UserController(($container->privates['mailchimp.api'] ??= new \DrewM\MailChimp\MailChimp($container->getEnv('MAILCHIMP_API_KEY'))), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)), new \Twilio\Rest\Client($container->getEnv('TWILIO_ACCOUNT_SID'), $container->getEnv('TWILIO_AUTH_TOKEN')));

        $instance->setContainer(($container->privates['.service_locator._FWhGxE'] ?? $container->load('get_ServiceLocator_FWhGxEService'))->withContext('App\\Controller\\UserController', $container));

        return $instance;
    }
}
