<?php

namespace ContainerYFR4lPE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUploadedFileService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BjMlj7V.Symfony\Component\HttpFoundation\File\UploadedFile' shared service.
     *
     * @return \Symfony\Component\HttpFoundation\File\UploadedFile
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BjMlj7V": it references class "Symfony\\Component\\HttpFoundation\\File\\UploadedFile" but no such service exists.');
    }
}
