# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration

services:
  # default configuration for services in *this* file
  App\EventListener\JwtCreatedListener:
    tags:
      - {
          name: kernel.event_listener,
          event: lexik_jwt_authentication.on_jwt_created,
          method: onJwtCreated,
        }
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    bind:
      $monthlySubscription: "%env(ID_STRIPE_SUBSCRIPTION_MONTHLY)%"
      $quarterlySubscription: "%env(ID_STRIPE_SUBSCRIPTION_QUARTERLY)%"
      $freeSubscription: "%env(ID_STRIPE_SUBSCRIPTION_FREE)%"
  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\Security\AccessDecisionManager:
    arguments: ["@security.access.decision_manager"]
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"
  DrewM\MailChimp\MailChimp: "@mailchimp.api"

  mailchimp.api:
    class: DrewM\MailChimp\MailChimp
    arguments:
      - "%env(MAILCHIMP_API_KEY)%"
  Twilio\Rest\Client:
    class: Twilio\Rest\Client
    arguments:
      - "%env(TWILIO_ACCOUNT_SID)%"
      - "%env(TWILIO_AUTH_TOKEN)%"
  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones
