<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GZAaMB6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GZAaMB6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GZAaMB6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'contentExclusive' => ['privates', '.errored..service_locator.GZAaMB6.App\\Entity\\ContentExclusive', NULL, 'Cannot autowire service ".service_locator.GZAaMB6": it needs an instance of "App\\Entity\\ContentExclusive" but this type has been excluded in "config/services.yaml".'],
        ], [
            'contentExclusive' => 'App\\Entity\\ContentExclusive',
        ]);
    }
}
