<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3H4ToqpService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3H4Toqp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3H4Toqp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'checkList' => ['privates', '.errored..service_locator.3H4Toqp.App\\Entity\\CheckList', NULL, 'Cannot autowire service ".service_locator.3H4Toqp": it needs an instance of "App\\Entity\\CheckList" but this type has been excluded in "config/services.yaml".'],
        ], [
            'checkList' => 'App\\Entity\\CheckList',
        ]);
    }
}
