<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckList2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3H4Toqp.App\Entity\CheckList' shared service.
     *
     * @return \App\Entity\CheckList
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3H4Toqp": it needs an instance of "App\\Entity\\CheckList" but this type has been excluded in "config/services.yaml".');
    }
}
