<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLayeringService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FZL4CLc.App\Entity\Layering' shared service.
     *
     * @return \App\Entity\Layering
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.FZL4CLc": it needs an instance of "App\\Entity\\Layering" but this type has been excluded in "config/services.yaml".');
    }
}
