<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailchimp_ApiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'mailchimp.api' shared autowired service.
     *
     * @return \DrewM\MailChimp\MailChimp
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/drewm/mailchimp-api/src/MailChimp.php';

        return $container->privates['mailchimp.api'] = new \DrewM\MailChimp\MailChimp($container->getEnv('MAILCHIMP_API_KEY'));
    }
}
