<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMailChimpControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MailChimpController' shared autowired service.
     *
     * @return \App\Controller\MailChimpController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MailChimpController.php';
        include_once \dirname(__DIR__, 4).'/vendor/drewm/mailchimp-api/src/MailChimp.php';

        $container->services['App\\Controller\\MailChimpController'] = $instance = new \App\Controller\MailChimpController(($container->privates['mailchimp.api'] ??= new \DrewM\MailChimp\MailChimp($container->getEnv('MAILCHIMP_API_KEY'))));

        $instance->setContainer(($container->privates['.service_locator._FWhGxE'] ?? $container->load('get_ServiceLocator_FWhGxEService'))->withContext('App\\Controller\\MailChimpController', $container));

        return $instance;
    }
}
