<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPerfumeTrialSheet2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aBN7K1Y.App\Entity\PerfumeTrialSheet' shared service.
     *
     * @return \App\Entity\PerfumeTrialSheet
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aBN7K1Y": it needs an instance of "App\\Entity\\PerfumeTrialSheet" but this type has been excluded in "config/services.yaml".');
    }
}
