<?php

namespace ContainerQzDRh2x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWishlistService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.OQsoty..App\Entity\Wishlist' shared service.
     *
     * @return \App\Entity\Wishlist
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.OQsoty.": it needs an instance of "App\\Entity\\Wishlist" but this type has been excluded in "config/services.yaml".');
    }
}
