<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQzDRh2x\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQzDRh2x/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQzDRh2x.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQzDRh2x\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQzDRh2x\App_KernelDevDebugContainer([
    'container.build_hash' => 'QzDRh2x',
    'container.build_id' => 'c017d69b',
    'container.build_time' => 1695878621,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQzDRh2x');
